import "@/assets/styles/styles.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Mainwrapper from "@/wrapper/main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Mainwrapper>{children}</Mainwrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
