import "@/assets/styles/styles.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Mainwrapper from "@/wrapper/main";
import { ThemeProvider } from "@/context/ThemeContext";
import ToastProvider from "@/components/ui/ToastProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AntdRegistry>
          <ThemeProvider>
            <ToastProvider />
            <Mainwrapper>{children}</Mainwrapper>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
